version: '2.1'

services:
  rating-data:
    image: rating-data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8082:8082
      - 5005:5005